# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hn < Formula
  desc "A terminal-based Hacker News client"
  homepage "https://github.com/heartleo/hn-cli"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/heartleo/hn-cli/releases/download/v0.0.4/hn_0.0.4_darwin_x86_64.tar.gz"
      sha256 "90c3606bddfd0c78e30bb4c32e848a63862eb72ed328340e526cf4265e5fcaf3"

      define_method(:install) do
        bin.install "hn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/heartleo/hn-cli/releases/download/v0.0.4/hn_0.0.4_darwin_arm64.tar.gz"
      sha256 "10c6341a6812a54ff09bea875207424cd6f04a6673bfe1a814e549f1ba2dd5f0"

      define_method(:install) do
        bin.install "hn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/heartleo/hn-cli/releases/download/v0.0.4/hn_0.0.4_linux_x86_64.tar.gz"
      sha256 "65102dc6f87c823d1a36c3fa3ca5991397ee580d9a958a7c805d307f7a14f161"
      define_method(:install) do
        bin.install "hn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heartleo/hn-cli/releases/download/v0.0.4/hn_0.0.4_linux_arm64.tar.gz"
      sha256 "5c4053181f0f81473a0ea0e838063ab2dd502c9e1e80cd8f41327687e37dcb17"
      define_method(:install) do
        bin.install "hn"
      end
    end
  end

  test do
    system "#{bin}/hn", "--version"
  end
end
