# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Subtrans < Formula
  desc "Translate SRT subtitle files using OpenAI-compatible APIs"
  homepage "https://github.com/heartleo/subtrans"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/heartleo/subtrans/releases/download/v0.0.2/subtrans_0.0.2_darwin_x86_64.tar.gz"
      sha256 "f478bf5bc3dd391731298296cf7a606fa6553544ac985962005df648a937cecf"

      define_method(:install) do
        bin.install "subtrans"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/heartleo/subtrans/releases/download/v0.0.2/subtrans_0.0.2_darwin_arm64.tar.gz"
      sha256 "68fc0612ffd8b6e89ead8837f3475400af7ab63df828029af9ccfb9bc18a0af9"

      define_method(:install) do
        bin.install "subtrans"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/heartleo/subtrans/releases/download/v0.0.2/subtrans_0.0.2_linux_x86_64.tar.gz"
      sha256 "390034f2a65676a7e6d0d25262b626dcc415fcf8f2b7ef2f6b0fb63e6d132bc8"
      define_method(:install) do
        bin.install "subtrans"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heartleo/subtrans/releases/download/v0.0.2/subtrans_0.0.2_linux_arm64.tar.gz"
      sha256 "a8137da85f2cce82d6095f61dc576229b053b01fe9955e6aa182df24bd13988a"
      define_method(:install) do
        bin.install "subtrans"
      end
    end
  end

  test do
    system "#{bin}/subtrans", "--version"
  end
end
