# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webdav115drive < Formula
  desc "A read-only WebDAV proxy for 115 Drive"
  homepage "https://github.com/heartleo/webdav-115drive"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/heartleo/webdav-115drive/releases/download/v0.1.3/webdav-115drive_v0.1.3_darwin_amd64.tar.gz"
      sha256 "f747c8b21655464e712285bbe24468dfd6d623fe159ba3d82d327875f9109b04"

      define_method(:install) do
        bin.install "webdav-115drive"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/heartleo/webdav-115drive/releases/download/v0.1.3/webdav-115drive_v0.1.3_darwin_arm64.tar.gz"
      sha256 "d59cb42083c239d8aeae0363398c92cf0d93eb85122e9d31e2e0c1515f689123"

      define_method(:install) do
        bin.install "webdav-115drive"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/heartleo/webdav-115drive/releases/download/v0.1.3/webdav-115drive_v0.1.3_linux_amd64.tar.gz"
      sha256 "cc7e7ce9b585cd0884cd089f439c48326085d7fe529a4dcc0a0ab257902381d9"
      define_method(:install) do
        bin.install "webdav-115drive"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heartleo/webdav-115drive/releases/download/v0.1.3/webdav-115drive_v0.1.3_linux_arm64.tar.gz"
      sha256 "b7d8aea3f80b20debbb3304c0c714b1a4fa4be5afdc7ffcabfc8b12039124e93"
      define_method(:install) do
        bin.install "webdav-115drive"
      end
    end
  end

  test do
    assert_path_exists bin/"webdav-115drive"
  end
end
