# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zlib < Formula
  desc "A CLI for Z-Library"
  homepage "https://github.com/heartleo/zlib"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/heartleo/zlib/releases/download/v0.0.7/zlib_0.0.7_darwin_x86_64.tar.gz"
      sha256 "f7e62e4f4b989e11bfd6f96a1da64886446b53b498bdc482fe32ad4c264d7a9e"

      define_method(:install) do
        bin.install "zlib"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/heartleo/zlib/releases/download/v0.0.7/zlib_0.0.7_darwin_arm64.tar.gz"
      sha256 "74e6958ff0b35c32204262f09b6db2396acc891022e9d0ea8c689a3f84e2541d"

      define_method(:install) do
        bin.install "zlib"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/heartleo/zlib/releases/download/v0.0.7/zlib_0.0.7_linux_x86_64.tar.gz"
      sha256 "448ab0cf7cadab477dbc3cae3d600c2dfecc8eae9cb9afdef7e6f04ce8c3273a"
      define_method(:install) do
        bin.install "zlib"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heartleo/zlib/releases/download/v0.0.7/zlib_0.0.7_linux_arm64.tar.gz"
      sha256 "69af9a6b4fba63c83378ec0360e96d47e413ad69692bfde153ddede9e552497f"
      define_method(:install) do
        bin.install "zlib"
      end
    end
  end

  test do
    system "#{bin}/zlib", "--version"
  end
end
