# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zlib < Formula
  desc "A CLI for Z-Library"
  homepage "https://github.com/heartleo/zlib"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/heartleo/zlib/releases/download/v0.0.8/zlib_0.0.8_darwin_x86_64.tar.gz"
      sha256 "2af0a27efbb36ac0b1339777edb3bde8e05490588bb57d3a724b41db9e406ea1"

      define_method(:install) do
        bin.install "zlib"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/heartleo/zlib/releases/download/v0.0.8/zlib_0.0.8_darwin_arm64.tar.gz"
      sha256 "2a63f10ef9d40c6308d6ba37831e57af0287f5855318e6880dfe98d0cbbff02b"

      define_method(:install) do
        bin.install "zlib"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/heartleo/zlib/releases/download/v0.0.8/zlib_0.0.8_linux_x86_64.tar.gz"
      sha256 "57c22ebd913c09a8f0cc783ead166cf002967a5ddd6b26e45b73f8657fb1356e"
      define_method(:install) do
        bin.install "zlib"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heartleo/zlib/releases/download/v0.0.8/zlib_0.0.8_linux_arm64.tar.gz"
      sha256 "934fa73ab3851ceacff006e8667f25328a1bc7a3944ead53df1fae410459c1c4"
      define_method(:install) do
        bin.install "zlib"
      end
    end
  end

  test do
    system "#{bin}/zlib", "--version"
  end
end
